# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Keep thingking and coding
tagline:          ""
description:      "null"
url:              https://codingingboy.github.io

author:
  name:           "coding boy"

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
